In [9]:
# 2.1 Вектора и их свойства // step 14

"""
Вход: 2 целых числа, разделенные пробелом.

Выход: массив NumPy из этих чисел.

Sample Input:

3 2
Sample Output:

[3 2]
"""

import numpy as np
a = np.array(input().split(), dtype = int) # принимаем значения из списка в массив
print(a)

[]


In [10]:
#L1 norm(L1 норма Манхетонская норма) - Manhetn
import numpy as np

vector_god = np.array([1, -2, 3, -4])

result_vector_god = np.linalg.norm(vector_god, ord = 1)

print(result_vector_god)

10.0


In [11]:
#L2 norm (L2 норма - Евклидова) - Evklid

import numpy as np

vector_friend = np.array([3, 4, 5])
result_vector_fried = np.linalg.norm(vector_friend)
print(result_vector_fried)

7.0710678118654755


In [12]:
#L бесконечность

vector_Vectorius = np.array([2, -5, 1, 7, -3, 0])
resuls_vector_Vectorius = np.linalg.norm(vector_Vectorius, ord = np.inf)
print(resuls_vector_Vectorius)

7.0


In [13]:
#2.3 Линейные операции над векторами - сложение
import numpy as np
v_a = np.array([1, 2, -1])
v_b = np.array([2, -2, 5])
def sum_of_vectors(v_a, v_b):
    summa = np.add(v_a, v_b)
    return summa
sum_of_vectors((1, 2,-1),(2, -2 , 5))


array([3, 0, 4])

In [14]:
#2.3 Линейные операции над векторами - вычитание
import numpy as np

v1 = np.array([2, 3, -1])
v2 = np.array([3, 1, 2])

subtraction = np.subtract(v1, v2)
print(subtraction)

[-1  2 -3]


In [15]:
#2.3 Линейные операции над векторами -  сложения/вычитания векторов и умножение вектора на число
import numpy as np

v1 = np.array([2, 3, 2])
v2 = np.array([1, 3, 2])

subtraction = v1 - v2
print(subtraction)

[1 0 0]


In [16]:
#2.3 Линейные операции над векторами - вычитание
# Нужно найти модуль разности векторов
import numpy as np
"""Описание задачи
Однажды им поступило задание - вычислить разность между двумя векторами а и b. В первый день они узнали координаты первого вектора a, который представлял собой могучую стрелу, выпущенную из лука крепкого лучника. Второй вектор b был как гладкий шар, который можно было пнуть ногой и он начнет скользить по склону горы. Бравые рыцари знали, что для того, чтобы выполнить задание, необходимо найти модуль разности этих векторов. С помощью своей длинной линейки Разность измерил длину разности векторов и нашел ее значение. А Модуль, используя свою мощную силу, возведенную в квадрат, нашел равную величину длины разности, которая была положительным числом. Так они и преуспели в этом задании, победив зло и защитив мир от тьмы и невежества.
"""
v1 = np.array([2, -1, 2])
v2 = np.array([4, 3.3, 2])

v3_subtraction = v1 - v2 # находим разность между векторами
v3_module = np.linalg.norm(v3_subtraction) # вычитаем модуль разности
print(v3_subtraction)
print(v3_module)


[-2.  -4.3  0. ]
4.742362280551751


In [17]:
#2.2 Линейные операции над векторами - вычитание
# Нужно найти модуль разности векторов

In [27]:
#2.2 Линейные операции над векторами - вычитание
"""ArithmeticError
Однажды Булочка, путешествуя по трехмерной вселенной, наткнулась на загадочную ломаную линию. Она начала следовать за ней, совершая различные повороты и перемещения. Координаты точек ломаной были следующими: А1(0,0,0) А2(1,1,0) А3(2,-2,0) А4(2,2,2) А5(3,1,-1). Булочка хочет вычислить длину этой загадочной линии. Помогите ей решить эту загадку и найти длину ломаной линии.

В поле ответа вставьте значение длины ломаной, округленное до одного знака после запятой. 
"""
import numpy as np

a1, a2, a3, a4, a5 = np.array([0,0,0]), np.array([1,1,0]), np.array([2,-2,0]), np.array([2,2,2]), np.array([3,1,-1])
b1 = a2 - a1 # находим длину отрезков
b2 = a3 - a2
b3 = a4 - a3
b4 = a5 - a4
module_b1 = np.linalg.norm(b1) # вычисляем модуль 
module_b2 = np.linalg.norm(b2)
module_b3 = np.linalg.norm(b3)
module_b4 = np.linalg.norm(b4)
print(module_b1 + module_b2 + module_b3 + module_b4) #суммируем модули

12.365251967896453
